<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="classes_user_tests.py" name="classes_user_tests.Test-20190510205016" skipped="0" tests="1" time="0.003" timestamp="2019-05-10T20:50:16">
	<testcase classname="classes_user_tests.Test" file="unittests/classes_user_tests.py" line="12" name="test_get_by_id" time="0.003" timestamp="2019-05-10T20:50:16">
		<error message="&lt;module 'user' from '/home/matheus/github/eswqa/classes/user.py'&gt; does not have the attribute '_select_all_by_userid'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/mock.py", line 1171, in patched
    arg = patching.__enter__()
  File "/usr/lib/python3.6/unittest/mock.py", line 1243, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python3.6/unittest/mock.py", line 1217, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'user' from '/home/matheus/github/eswqa/classes/user.py'> does not have the attribute '_select_all_by_userid'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
